#!/usr/bin/env bash
set -e

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
pip install .
cd ..

git clone https://github.com/cwindolf/dartsort.git
cd dartsort
pip install -e .[full]
cd ..